### PR TITLE
fix: ensure timers are cleaned up on service destroy

### PR DESCRIPTION
**Pull request by makepanic**

### CODE REVIEW

**Comment by makepanic** [comment]
I've noticed this because many of our acceptance tests lead into a flash appearing in the end (e.g. error flash or confirmation flash).

When investigating, there was always a dangling timer that slowed the test down:



With this PR:

**Comment by sbatson5** [comment]
Awesome catch 👍 

I need to investigate the Circle failure -- it's unrelated to your change

**Comment by abhilashlr** [comment]
@makepanic If you rebase with current master I believe it should pass this PR.

**Comment by makepanic** [comment]
rebased it onto the current master

**Pull request merged**
