### PR TITLE
remove deprecated usage of Ember.copy

### PR DESCRIPTION
**Pull request by bgentry**
Fixes #173. Fixes deprecations in Ember v3.3.

### CODE REVIEW

**Comment by bgentry** [comment]
This is a bit annoying to reproduce since CircleCI has been down all day. Running `yarn test` locally, I am able to reproduce the failures. However, these exact same failures also occur on `master`:

```
not ok 35 Chrome 67.0 - FlashMessageComponent: it renders with the right props
    ---
        actual: >
            false
        expected: >
            true
        stack: >
                at Ember.run.next (http://localhost:7357/assets/tests.js:318:14)
                at invoke (http://localhost:7357/assets/vendor.js:27485:24)
                at Queue.flush (http://localhost:7357/assets/vendor.js:27403:25)
                at DeferredActionQueues.flush (http://localhost:7357/assets/vendor.js:27562:31)
                at Backburner._end (http://localhost:7357/assets/vendor.js:28008:42)
                at Backburner.end (http://localhost:7357/assets/vendor.js:27750:18)
        message: >
            it sets `active` to true after rendering
        negative: >
            false
        Log: |
    ...
```

So I believe this is an issue that needs to be fixed separately.

**Comment by izelnakri** [comment]
@poteto can we update this package?

**Comment by bgentry** [comment]
Just to restate: the test failures here also occur on master. Might want to open a separate issue about that but it shouldn’t necessarily block this PR (as long as you can verify the failures are the same, as I did).

**Comment by Dhaulagiri** [comment]
released in 1.6.5

**Pull request merged**
