### PR TITLE
extendTimeout on sticky message

### PR DESCRIPTION
**Pull request by sbatson5**
Closes: https://github.com/poteto/ember-cli-flash/issues/228

## What's in this PR?

This PR adds the `exiting` class to messages that are sticky but have an extended timeout. This will honor exiting animations for messages that are clicked to dismiss.

Sticky message being dismissed with styling applied to `exiting` class:
exiting-message

### CODE REVIEW

**Comment by sbatson5** [comment]
@sdhull you had mentioned wanting address the issue of exiting animations when messages are `sticky`. Would you have time to review this PR using `ember-concurrency` to handle that?  Finally got around to wrapping it up 😛

**Comment by sdhull** [comment]
One note: should remove my note in the Readme about `.exiting` not working with `stick: true` 😉

**Comment by sbatson5** [comment]
@Dhaulagiri or @poteto mind giving this a review before I merge?

**Comment by Dhaulagiri** [comment]
@sbatson5 without being too familiar with ember-concurrency (somehow have not used it) this looks ok to my eyes

**Pull request merged**
