### PR TITLE
ember 2.0 doesn't have EnumerableUtils, it requires ES5 which ships

### PR DESCRIPTION
**Pull request by stefanpenner**
map/forEach

### CODE REVIEW

**Comment by stefanpenner** [comment]
cc @raytiley

**Comment by gmurphey** [comment]
Seems like some tests are still using `EnumerableUtils.forEach`.

**Comment by poteto** [comment]
Sorry about this, I already fixed this issue before I saw this PR :(

**Comment by stefanpenner** [comment]
@poteto NP, i suspect your PR was without test failures :)

**Pull request closed without merging**
