### PR TITLE
1.8.1

### PR DESCRIPTION
**Pull request by sbatson5**
Release 1.8.1

### CODE REVIEW

**Comment by sbatson5** [comment]
@poteto / @Dhaulagiri could I get a release of this to fix the event listener bug?

**Comment by dcyriller** [comment]
According to `npm owner ls`, you also have publishing rights @sbatson5 😄

**Comment by sbatson5** [comment]
@dcyriller Yeah, I had reached out to @poteto about this but apparently there is a "One Time Password" set up for publication and I am not getting a notification on publish 🤷‍♂ So it keeps failing for me

**Comment by poteto** [comment]
@sbatson5 I can publish this one. I enabled 2FA for all my npm packages as one of the easiest ways to do something shady is by hijacking the accounts of maintainers.

You might want to check out how to [setup 2fa](https://docs.npmjs.com/about-two-factor-authentication) for your npm account. If you are having issues maybe [npm support](https://www.npmjs.com/support) can help.

**Comment by poteto** [comment]
Published: https://www.npmjs.com/package/ember-cli-flash/v/1.8.1

**Pull request merged**
