### PR TITLE
add qunit-dom and update component tests

### PR DESCRIPTION
**Pull request by sbatson5**
## What's in this PR?

As discussed here: https://github.com/poteto/ember-cli-flash/pull/277#discussion_r206132419
We didn't want to add this dependency until it was actually used.  This PR updates the tests to use qunit-dom when applicable.  Also updates the modules for testing the component (integration and unit).

### CODE REVIEW

**Comment by Dhaulagiri** [comment]
Looks like the tests are unhappy

**Comment by sbatson5** [comment]
Yeah, seems to only be failing on certain ember version. I can investigate this weekend

**Comment by Dhaulagiri** [comment]
@sbatson5 is this something you think you'll try to land at some point?

**Comment by sbatson5** [comment]
@Dhaulagiri I've been meaning to come back to this, but work has been eating up too much time.  I have to figure out why this fails in one particular instance.

I can close for now to reduce repo noise

**Pull request closed without merging**
